### PR TITLE
Added Native Soundcloud Support

### PR DESCRIPTION
**Pull request by jnomikos**
Hello,

For my own purposes, I have integrated the soundcloud downloader package with discord-music-player to allow for native soundcloud support. Of course, doing this may have introduced a few bugs, but it works with my implementation. I am putting this pull request here to potentially contribute if you wish to add my code, or to edit it so that it fits. My implementation is a bit janky, but I feel that with a little bit of work, it could add a lot.

Thank you so much, if you have any questions please contact me. And if this pull req isn't accepted, I completely understand. 

Sincerely,

John Nomikos.

### CODE REVIEW

**Comment by slienlaffa** [comment]
1091 files changed omg, you clearly did something wrong, like deleting .gitignore or something, I will recommend getting rid of those commits and any unnecessary change

**Comment by jnomikos** [comment]
> 1091 files changed omg, you clearly did something wrong, like deleting .gitignore or something, I will recommend getting rid of those commits and any unnecessary change

Yeah I deleted the gitignore since it wouldn't let me download from git. I'll fix

**Comment by SushiBtw** [comment]
As @jnomikos said, please upload the files only. You uploaded the build + node modules too. Please fix so we can take a look.

**Comment by jnomikos** [comment]
> As @slienlaffa said, please upload the files only. You uploaded the build + node modules too. Please fix so we can take a look.
> 
> 

Sounds good. I don't have my computer right now so I'll be moving, but I'll do that when I am able to (sometime after the 12th).

**Comment by SushiBtw** [comment]
I can't merge it @jnomikos as you pushed all files, even the build ones. Please review your pr and make a new one without pushing everything (look gitignore)

**Pull request closed without merging**
