### PR TITLE
v6.3.0 Updates

### PR DESCRIPTION
**Pull request by SushiBtw**
**Changes with v6.3.0:**
- [x] Fix YouTube issues with Vevo Music (#22),
- [x] Add ``playlist`` method (#20),
- [x] Add ``toggleLoop(GuildID)`` method and mark ``setRepeatMode(GuildID, boolean)`` as valid but not recommended (#17),
- [x] Bump NodeJS version to v14 - [READ MORE](https://github.com/discordjs/discord.js/pull/5067),
- [x] Add ``timeout: int`` option [leaves the voice channel after X milliseconds] (#27),
- [x] README.md Update,
- [x] Minor Fixes.

### CODE REVIEW

**Comment by ToledoSDL** [comment]
i can help you?

**Comment by SushiBtw** [comment]
If you have any suggestions, sure - just create a pull request.

**Comment by SushiBtw** [comment]
Bumped NodeJS to minimum version of v14.0.0 - [Read More Here](https://github.com/discordjs/discord.js/issues/5119).
Added ``timeout`` option.

**Comment by SushiBtw** [comment]
Added ``playlist`` method (#20).

**Comment by SushiBtw** [comment]
Fixed YouTube vevo issues (#22).
Fixed Author shot (#24).
Added ``toggleLoop`` method (#17).

**Pull request merged**
