### PR TITLE
Fixes some songs not being played from youtube. / queueDestroyed-event added

### PR DESCRIPTION
**Pull request by Thyrador**
See issues https://github.com/SushiBtw/discord-music-player/issues/219 and https://github.com/SushiBtw/discord-music-player/issues/231 for details.

### CODE REVIEW

**Comment by Thyrador** [comment]
I just added a **queueDestroyed** event in case someone else find it useful.
It fires when the queue was manually stopped or the connection ends, which causes the queue to destroy itself.

**Comment by warior456** [comment]
does this fix the 2 songs i have found that don't play then?

**Comment by Thyrador** [comment]
> does this fix the 2 songs i have found that don't play then? (https://www.youtube.com/watch?v=vdcddjV0l5o&ab_channel=CrunchyrollCollection and https://www.youtube.com/watch?v=AODD6vPbNFk&ab_channel=Darksacreurx)

Please remove unnecessary clutter from your urls:

https://www.youtube.com/watch?v=vdcddjV0l5o&ab_channel=CrunchyrollCollection -> works
https://www.youtube.com/watch?v=AODD6vPbNFk&ab_channel=Darksacreurx -> also works

**Review by SushiBtw — APPROVED** [review]
Seems working for me, pushing that today.

Thanks @Thyrador <3

**Comment by Thyrador** [comment]
I'm happy to help :)
Thanks for approving :)

**Comment by SushiBtw** [comment]
Pushing today, thanks again!

**Comment by SushiBtw** [comment]
Pushed - https://www.npmjs.com/package/discord-music-player/v/8.3.0.

**Pull request merged**
