### PR TITLE
Update @discordjs/voice to fix keepAlive timeout

### PR DESCRIPTION
**Pull request by joshbrucker**
See PR https://github.com/SushiBtw/discord-music-player/pull/322 and Issue https://github.com/SushiBtw/discord-music-player/issues/323

We no longer need to implement a manual quick fix. Discord.js [released a new version](https://github.com/discordjs/discord.js/releases/tag/%40discordjs%2Fvoice%400.15.0) that addresses the keepAlive 60 second timeout issue. This PR updates @discordjs/voice to that version.

@SushiBtw - this is really important, because without an update, all connections will continue to time out after 60 seconds.

### CODE REVIEW

**Review by RaFaTEOLI — APPROVED** [review]

**Comment by EclipseGame18** [comment]
May I also add that while we wait for an official release, we can manually override the @discordjs/voice package version for discord-music-player in your own package.json:
```
"overrides": {
      "discord-music-player": {
        "@discordjs/voice": "^0.16.0"
      }
    }
```
hope this helps!

**Comment by Klairm** [comment]
Why is this not being merged?

**Comment by jnomikos** [comment]
Looks good to me. This needs to be merged ASAP

**Comment by Narkeus2230** [comment]
> [EclipseGame18](/EclipseGame18)

Hello this did not work on me.

My package.json:
```{
  "name": "masea",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node index.js"
  },
  "overrides": {
      "discord-music-player": {
        "@discordjs/voice": "^0.16.0"
      }
    },
  "author": "Maddox",
  "license": "ISC",
  "dependencies": {
    "@discordjs/opus": "^0.9.0",
    "@discordjs/voice": "^0.16.0",
    "chalk": "^4.1.2",
    "dblapi.js": "^2.4.1",
    "discord-music-player": "^9.1.1",
    "discord.js": "^13.16.0",
    "ffmpeg": "^0.0.4",
    "ffmpeg-static": "^5.1.0",
    "fs": "^0.0.1-security",
    "isomorphic-unfetch": "^4.0.2",
    "lyrics-finder": "^21.7.0",
    "moment": "^2.29.4",
    "moment-duration-format": "^2.3.2",
    "path": "^0.12.7",
    "wio.db": "^4.0.9",
    "youtube-sr": "^4.3.4",
    "ytdl-core": "^4.11.5"
  }
}
```
As you see it is still 0.11.0 
[picture 1](https://cdn.discordapp.com/attachments/940631268205424640/1142456146918121513/djs_voice.JPG)
[picture 2](https://cdn.discordapp.com/attachments/940631268205424640/1142456146918121513/djs_voice.JPG)

**Comment by EclipseGame18** [comment]
try putting the overrides after your dependencies:
```
"dependencies": {
    "@discordjs/opus": "^0.9.0",
    "@discordjs/voice": "^0.16.0",
    "@distube/ytdl-core": "^4.11.16",
    "apple-music-metadata": "^2.0.1",
    "discord-command-cooldown": "^1.0.9",
    "discord-economy-super": "^1.7.6",
    "discord-image-generation": "^1.4.25",
    "discord-music-player": "^9.1.1",
    "discord-tts": "^1.2.2",
    "discord-ytdl-core": "^5.0.4",
    "discord.js": "^14.9.0",
    "domhandler": "^5.0.3",
    "ffmpeg-static": "^5.1.0",
    "htmlparser2": "^8.0.2",
    "isomorphic-unfetch": "^4.0.2",
    "libsodium-wrappers": "^0.7.11",
    "ms": "^2.1.3",
    "node-gyp": "^9.3.1",
    "node-opus": "^0.3.3",
    "opusscript": "^0.0.8",
    "spotify-url-info": "^3.2.3",
    "weather-js": "^2.0.0",
    "wokcommands": "^2.1.9",
    "youtubei": "^1.1.2",
    "ytdl-core": "npm:@distube/ytdl-core@^4.11.16",
    "ytsr": "^3.8.2"
  },
  "overrides": {
    "discord-music-player": {
      "@discordjs/voice": "^0.16.0"
    }
  }
```

**Pull request closed without merging**
