### PR TITLE
Changed Utils.search() function

### PR DESCRIPTION
**Pull request by elbkr**
I changed the function because it causes a conflict with JavaScript [String.prototype.search()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/search)

from .search() to .searchSong()

You should also change it in `Utils.d.ts`

### CODE REVIEW

**Review by SushiBtw — CHANGES_REQUESTED** [review]
If you want the search function to be changed, please manage to change it's all uses in the code.

**Comment by elbkr** [comment]
> If you want the search function to be changed, please manage to change it's all uses in the code.

Okay, and an update on this problem:

It only appears when you require Utils like this:
```js
const {Utils} = require("discord-music-player") // it shows the problem
const DMP = require("discord-music-player") // it doesn't show the problem
```

**Comment by SushiBtw** [comment]
> > If you want the search function to be changed, please manage to change it's all uses in the code.
> 
> Okay, and an update on this problem:
> 
> It only appears when you require Utils like this:
> 
> ```js
> const {Utils} = require("discord-music-player") // it shows the problem
> const DMP = require("discord-music-player") // it doesn't show the problem
> ```

You need to implement it in the code, as Queue.ts uses it.

**Comment by elbkr** [comment]
I'll change it now

**Comment by elbkr** [comment]
wait I accidently deleted my branch

**Pull request closed without merging**
