### PR TITLE
Feature to Fetch All Tracks from Spotify Playlist and Refactor Spotify Url Info Deprecation

### PR DESCRIPTION
**Pull request by RaFaTEOLI**
- Added api call to fetch remaining playlist tracks using a guest token from spotify.
- Replaced spotify-url-info dependency on fetching tracks with spotify official api.
- Upgraded node-ytsr: https://github.com/TimeForANinja/node-ytsr/commit/d03b4c22b15026a4986325bf26ab9a65bd6a9d3f
- Added explicit typing for adapter to fix typescript error.

### CODE REVIEW

**Comment by SushiBtw** [comment]
Hi! Pushing this today

**Comment by RaFaTEOLI** [comment]
Any updates on this?

**Comment by RaFaTEOLI** [comment]
Pull request updated and tested! @SushiBtw please check, if you have any question let me know.

**Comment by RaFaTEOLI** [comment]
Closing this because i created a new one here: https://github.com/SushiBtw/discord-music-player/pull/329

**Pull request closed without merging**
